### PR TITLE
Use usernameAttr and iconUrlAttr attributes instead of fixed values

### PR DESCRIPTION
**Pull request by nelsonong**

### CODE REVIEW

**Comment by ddebrunner** [comment]
Can we be consistent on the naming of parameters, using "Attribute" or "Attr" consistently.

I personally not sure why we need to have "attribute" in the name at all.

**Comment by nelsonong** [comment]
Yes I made all the TupleAttribute type parameters use "Attr".
I have the "Attr" to make it clear to the user that they're specifying the name of an attribute and not an actual fixed value.

**Comment by ddebrunner** [comment]
Technically they are specifying the attribute, not the name of it.

**Comment by ddebrunner** [comment]
> `@Parameter(...)`
> public void setMessageAttribute

this will result in a parameter called `messageAttribute`.

**Comment by ddebrunner** [comment]
Toolkits in the products seem to use a mix of not having any form of attribute in the name, `Attr` or `Attribute`. Pity we can't be consistent across all toolkits.
@chanskw

**Comment by ddebrunner** [comment]
The new Kafka operators are using 'Attribute', e.g. 'messageAttribute'.

https://github.com/IBMStreams/streamsx.kafka/issues/17#issuecomment-307842552

**Comment by nelsonong** [comment]
Using 'Attribute' now.

**Pull request merged**
